-- Construction Material API initial schema (PostgreSQL).
-- Column names use snake_case to match Hibernate's default physical naming strategy,
-- and types are chosen so `spring.jpa.hibernate.ddl-auto=validate` passes.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    avatar_url    VARCHAR(255),
    active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMPTZ    NOT NULL,
    updated_at          TIMESTAMPTZ    NOT NULL,
    name                VARCHAR(255)   NOT NULL,
    category            VARCHAR(255)   NOT NULL,
    cost_price          NUMERIC(19, 2) NOT NULL DEFAULT 0,
    selling_price       NUMERIC(19, 2) NOT NULL DEFAULT 0,
    stock_quantity      INTEGER        NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER        NOT NULL DEFAULT 0,
    unit                VARCHAR(255)   NOT NULL DEFAULT 'pcs',
    description         VARCHAR(1000),
    image_url           VARCHAR(255),
    barcode             VARCHAR(255)
);

CREATE TABLE customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ    NOT NULL,
    updated_at    TIMESTAMPTZ    NOT NULL,
    name          VARCHAR(255)   NOT NULL,
    phone         VARCHAR(255),
    email         VARCHAR(255),
    address       VARCHAR(500),
    loyalty_points INTEGER       NOT NULL DEFAULT 0,
    balance       NUMERIC(19, 2) NOT NULL DEFAULT 0,
    discount_rate NUMERIC(6, 4)  NOT NULL DEFAULT 0
);

CREATE TABLE suppliers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ    NOT NULL,
    updated_at TIMESTAMPTZ    NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    phone      VARCHAR(255),
    email      VARCHAR(255),
    address    VARCHAR(500),
    payable    NUMERIC(19, 2) NOT NULL DEFAULT 0
);

CREATE TABLE warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    code       VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    location   VARCHAR(255),
    capacity   INTEGER      NOT NULL DEFAULT 0,
    used       INTEGER      NOT NULL DEFAULT 0,
    incoming   INTEGER      NOT NULL DEFAULT 0,
    outgoing   INTEGER      NOT NULL DEFAULT 0,
    is_primary BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE inventory_movements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    product_id BIGINT       NOT NULL REFERENCES products (id),
    type       VARCHAR(255) NOT NULL,
    quantity   INTEGER      NOT NULL,
    note       VARCHAR(500)
);

CREATE TABLE sales (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL,
    invoice_number  VARCHAR(255)   NOT NULL UNIQUE,
    customer_id     BIGINT         REFERENCES customers (id),
    discount        NUMERIC(19, 2) NOT NULL DEFAULT 0,
    tax_rate        NUMERIC(6, 4)  NOT NULL DEFAULT 0,
    payment_method  VARCHAR(255)   NOT NULL,
    amount_received NUMERIC(19, 2) NOT NULL DEFAULT 0,
    status          VARCHAR(255)   NOT NULL,
    cashier_name    VARCHAR(255)   NOT NULL,
    subtotal        NUMERIC(19, 2) NOT NULL DEFAULT 0,
    tax             NUMERIC(19, 2) NOT NULL DEFAULT 0,
    grand_total     NUMERIC(19, 2) NOT NULL DEFAULT 0,
    change_due      NUMERIC(19, 2) NOT NULL DEFAULT 0
);

CREATE TABLE sale_lines (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ    NOT NULL,
    updated_at    TIMESTAMPTZ    NOT NULL,
    sale_id       BIGINT         NOT NULL REFERENCES sales (id),
    product_id    BIGINT         NOT NULL REFERENCES products (id),
    product_name  VARCHAR(255)   NOT NULL,
    quantity      INTEGER        NOT NULL,
    unit_price    NUMERIC(19, 2) NOT NULL,
    line_discount NUMERIC(19, 2) NOT NULL DEFAULT 0
);

CREATE TABLE deliveries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    reference     VARCHAR(255) NOT NULL UNIQUE,
    customer_name VARCHAR(255) NOT NULL,
    address       VARCHAR(500) NOT NULL,
    driver_name   VARCHAR(255),
    vehicle       VARCHAR(255),
    status        VARCHAR(255) NOT NULL,
    eta           TIMESTAMPTZ,
    items_summary VARCHAR(1000),
    note          VARCHAR(500)
);

CREATE INDEX idx_inventory_movements_product ON inventory_movements (product_id);
CREATE INDEX idx_sale_lines_sale ON sale_lines (sale_id);
CREATE INDEX idx_sale_lines_product ON sale_lines (product_id);
CREATE INDEX idx_sales_status ON sales (status);
CREATE INDEX idx_sales_created_at ON sales (created_at);
CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_deliveries_status ON deliveries (status);
